server:
  port: 8080
  context-path: /
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
      config:
        server:
          git:
            uri: https://github.com/Kingson4Wu/spring-cloud-config.git
